title: NHB Lab
baseurl: ""
url: "https://www.xiaoyangxulab.com"


collections:
  publications:
    output: true
    permalink: /publications/:name/
  news:
    output: true
    permalink: /news/:title/
