title: NHB Lab
baseurl: "/nhblab.github.io"
url: "https://constantine-adol.github.io"


collections:
  publications:
    output: true
    permalink: /publications/:name/
  news:
    output: true
    permalink: /news/:title/
